server:
    error:
        include-stacktrace: NEVER
spring:
  h2:
    console:
    enabled: true
    path: /h2-console
    datasource:
    username: sa
    password:

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: full

